version: 0.2

env:
  variables:
    NODE_ENV: 'production'
  parameter-store:
    NPM_TOKEN: /secrets/ops/us-east-1/build-pipelines/shared/npm_token

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies..."
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - npm install

  build:
    commands:
      - echo "Running lint..."
      - npm run lint
      - echo "Running format check..."
      - npm run format:check
      - echo "Setting version from git tag..."
      - npm version --no-git-tag-version $CODEBUILD_SOURCE_VERSION
      - echo "Publishing package..."
      - npm publish

  post_build:
    commands:
      - echo "Package published successfully"
