version: 0.2

env:
  variables:
    NODE_ENV: 'development'
  parameter-store:
    NPM_TOKEN: /secrets/ops/us-east-1/build-pipelines/shared/npm_token

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "=== DEBUG: Install Phase Started ==="
      - echo "Node.js version:" && node --version
      - echo "npm version:" && npm --version
      - echo "Current directory:" && pwd
      - echo "Files in directory:" && ls -la
      - echo "Environment NODE_ENV:" && echo $NODE_ENV
      - echo "Creating .npmrc file..."
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - echo "Contents of .npmrc:" && cat .npmrc
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "=== DEBUG: Build Phase Started ==="
      - echo "Running lint..."
      - npm run lint
      - echo "=== DEBUG: Build Phase Completed ==="

  post_build:
    commands:
      - echo "=== DEBUG: Post-build Phase ==="
      - echo "Build completed successfully"
