version: 0.2

env:
  variables:
    NODE_ENV: 'development'
  parameter-store:
    NPM_TOKEN: /secrets/ops/us-east-1/build-pipelines/shared/npm_token

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Running lint..."
      - npm run lint
      - echo "Running format check..."
      - npm run format:check

  post_build:
    commands:
      - echo "Build completed successfully"
